"""Add patient, registration, appointment, clinician tables

Revision ID: 86e3971ca20c
Revises: fb0a7ec5439e
Create Date: 2026-07-13 00:08:28.438154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e3971ca20c'
down_revision: Union[str, Sequence[str], None] = 'fb0a7ec5439e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_counters',
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=False)
    op.create_table('registration_id_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_seq', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinician_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('note_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('conversation_turns', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_foreign_key(None, 'conversation_turns', 'intake_sessions', ['session_id'], ['id'])
    op.add_column('intake_sessions', sa.Column('visit_classification', sa.String(length=20), server_default='ROUTINE', nullable=False))
    op.add_column('intake_sessions', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.add_column('intake_sessions', sa.Column('appointment_number', sa.Integer(), nullable=True))
    op.add_column('intake_sessions', sa.Column('chief_complaint_text', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'intake_sessions', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intake_sessions', type_='foreignkey')
    op.drop_column('intake_sessions', 'chief_complaint_text')
    op.drop_column('intake_sessions', 'appointment_number')
    op.drop_column('intake_sessions', 'patient_id')
    op.drop_column('intake_sessions', 'visit_classification')
    op.drop_constraint(None, 'conversation_turns', type_='foreignkey')
    op.alter_column('conversation_turns', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('clinician_notes')
    op.drop_table('registration_id_counter')
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('appointment_counters')
    # ### end Alembic commands ###
